import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LucideGitPullRequestCreate } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="container">
          <main className="flex min-h-screen flex-col items-center justify-center gap-2 sm:gap-3 md:gap-5 py-5 ">
            {children}
          </main>
        </section>
      </body>
    </html>
  );
}